# Generated by Django 5.2.6 on 2025-10-02 18:14

import usuarios.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=usuarios.encrypted_fields.EncryptedField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=usuarios.encrypted_fields.EncryptedField(blank=True, max_length=20, null=True),
        ),
    ]
