# Generated by Django 5.2.6 on 2025-10-02 18:37

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_cpf_alter_customuser_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('duracao_minutos', models.IntegerField(default=30)),
                ('tipo_consulta', models.CharField(choices=[('presencial', 'Presencial'), ('telemedicina', 'Telemedicina')], default='presencial', max_length=12)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=10)),
                ('link_consulta', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(limit_choices_to={'tipo_usuario': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
