# Generated by Django 5.2.6 on 2025-10-03 00:32

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anotacao', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame'), ('diagnostico', 'Diagnóstico'), ('prescricao', 'Prescrição'), ('evolucao', 'Evolução')], default='consulta', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('sintomas', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('prescricao_medicamentos', models.TextField(blank=True)),
                ('exames_solicitados', models.TextField(blank=True)),
                ('pressao_arterial', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('temperatura', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('frequencia_cardiaca', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios', to='usuarios.agendamento')),
                ('medico', models.ForeignKey(limit_choices_to={'tipo_usuario': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
