# Generated by Django 5.2.6 on 2025-10-09 17:13

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_prontuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(choices=[('sangue', 'Exame de Sangue'), ('urina', 'Exame de Urina'), ('imagem', 'Exame de Imagem'), ('cardiologico', 'Exame Cardiológico'), ('neurologico', 'Exame Neurológico'), ('outros', 'Outros')], max_length=20)),
                ('nome_exame', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('resultado', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('observacoes', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('valores_referencia', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('data_resultado', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('coletado', 'Coletado'), ('processando', 'Processando'), ('finalizado', 'Finalizado'), ('entregue', 'Entregue')], default='solicitado', max_length=15)),
                ('laboratorio', models.CharField(blank=True, max_length=200)),
                ('medico', models.ForeignKey(limit_choices_to={'tipo_usuario': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='exames_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='exames_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
