# Generated by Django 5.2.6 on 2025-10-10 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_agendamento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('exame', 'Exame'), ('procedimento', 'Procedimento'), ('dieta', 'Dieta')], default='medicamento', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('medicamentos', models.TextField(blank=True, help_text='Lista de medicamentos, dosagens e posologias', null=True)),
                ('posologia', models.TextField(blank=True, help_text='Instruções de uso detalhadas', null=True)),
                ('exames_solicitados', models.TextField(blank=True, help_text='Exames ou procedimentos solicitados', null=True)),
                ('data_prescricao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(help_text='Data até quando a receita é válida')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(limit_choices_to={'tipo_usuario': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='receitas_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='receitas_paciente', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='usuarios.prontuario')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'usuarios_receita',
                'ordering': ['-data_prescricao'],
            },
        ),
    ]
